### PR TITLE
Fix template.update kafka message formatting

### PR DESCRIPTION
**Pull request by jsiloto**

### CODE REVIEW

**Comment by jsiloto** [comment]
The last change should break both iotagent-java and iotagent-nodejs that read the "affected" field to invalidate cache

**Comment by mmagr** [comment]
:thinking: 
This will most likely require changes to `iotagent-(java|nodejs)` libs.
Since node's agents do not rely on template updates directly, I think it's ok to change this.
In the meantime, I'll update `iotagent-nodejs` to take into account changes in event schema.

**Comment by mmagr** [comment]
I trust you'll update `iotagent-java` @jsiloto ?

**Comment by jsiloto** [comment]
Yes

**Pull request merged**
